#Esto es para produccion y el despliegue
spring.application.name=marMotorBackend
spring.profiles.active=dev

# Datos de tu MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/marmotor_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true