#Esto es para produccion y el despliegue
spring.application.name=marMotorBackend
spring.profiles.active=dev

# Datos de tu MySQL local
spring.datasource.url=***********
spring.datasource.username=******
spring.datasource.password=*******

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Credenciales de Cloudinary
cloudinary.cloud_name=*******
cloudinary.api_key=************
cloudinary.api_secret=**************

# Aumentar tamaño máximo para subir fotos (Ej: 10MB por foto, 50MB en total por petición)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=80MB