#Esto es para produccion y el despliegue
spring.application.name=marMotorBackend
spring.profiles.active=prod

# Datos de tu MySQL nuve
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=${PORT:8080}

# Credenciales de Cloudinary
cloudinary.cloud_name=${CL_NAME}
cloudinary.api_key=${CL_KEY}
cloudinary.api_secret=${CL_SECRET}

# Aumentar tamaño máximo para subir fotos (Ej: 10MB por foto, 50MB en total por petición)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=80MB

# Seguridad jwt
jwt.secret=${JWT_S}

# Correo de recuperacion
# --- CONFIGURACIÓN DE EMAIL (Cartero) ---
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.reset-password-url=${FRONTEND_URL}/auth/reset-password?token=