services:
  mysql-db:
    image: mysql:8.0
    container_name: marmotor-mysql
    restart: always
    environment:
      # MySQL creará esta base de datos al iniciar
      - MYSQL_DATABASE=marmotor_db
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      # Usamos la contraseña de tu .env
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
